version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bomb0069-hello-sam"
s3_bucket = "aadesh-cxe-test"
s3_prefix = "bomb0069-hello-sam"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
